<?php $_url = $this->getTheLink(); ?>
<?php if( $_url !== '' ):?>
<div class="digidennis-quickpay-dolink">
    <p>Der er endnu ikke registreret betaling for din ordre.</p>
    <a style="background-color: #324b7d;
              padding: 6px 12px;
              text-align:center;
              font-weight: normal;
              box-shadow: 0 1px 5px -1px rgba(0,0,0,0.4);
              border-color: #324b7d;
              border-radius: 2px;" href="<?php echo $_url ;?>" title="Betal for din ordre" >Betal for din ordre</a>
</div>
<?php endif; ?>